name: shopping_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^5.6.1
  awesome_notifications: ^0.10.0
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ads0.jpg
    - assets/ads1.jpg
    - assets/gaun1.jpg
    - assets/gaun2.jpg
    - assets/gaun3.jpg
    - assets/gaun4.jpg
    - assets/gaun5.jpg
    - assets/gaun6.jpg
    - assets/gaun7.jpg
